tools/ipc: use closesocket() instead of close() on Windows
Fixes the following compile warning on the MinGW CI:
../../ngl-tools/ngl-ipc.c:354:9: warning: implicit declaration of function 'close'

This was forgotten in 139b5ec4d8072831061f2b689bc7650deb419029.