utils: remove unnecessary Fileapi.h and Handleapi.h includes
The Microsoft documentation suggests that Windows.h should be included
instead of Fileapi.h and/or Handleapi.h headers. Windows.h takes care of
including a bunch of core headers for the user (Fileapi.h, Handleapi.h,
Profileapi.h to name a few).

This resolves the following compile error on MSVC:
winnt.h(173,1): fatal error C1189: #error: "No Target Architecture".